# SAM configuration file for AWS Serverless Workshop
version = 0.1

[default]
[default.global.parameters]
# STUDENTS: change this to your assigned ID (e.g. todo-workshop-01)
stack_name = "todo-workshop-13"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = false

[default.deploy.parameters]
region = "ap-southeast-1"

# Shared instructor-managed artifacts bucket. DO NOT change
s3_bucket = "todo-workshop-artifacts-141922114492"
# STUDENTS: change this to your assigned ID (e.g. todo-workshop-01)
s3_prefix = "todo-workshop-13"

capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

# CloudFormation execution role (instructor-managed)
role_arn = "arn:aws:iam::141922114492:role/TodoWorkshopCfnRole"

[default.package.parameters]
s3_bucket = "todo-workshop-artifacts-141922114492"
# STUDENTS: change this to your assigned ID (e.g. todo-workshop-01)
s3_prefix = "todo-workshop-13"